"""
    Program 1: printing a song or poem
"""

print("Once upon a time not so long ago\n\n")
print("He's down on his luck, it's tough, so tough")
print("Gina works the diner all day working for her man")
print("She brings home her pay, for love, for love")
print("She says we've got to hold on to what we've got")
print("It doesn't make a difference if we make it or not")
print("We've got each other and that's a lot for love")
print("We'll give it a shot")
print("Woah, we're half way there")
print("Woah, livin' on a prayer")
print("Take my hand, we'll make it I swear")
print("Woah, livin' on a prayer")
print("Tommy's got his six-string in hock")
print("Now he's holding in what he used to make it talk")
print("So tough, it's tough")
print("Gina dreams of running away")
print("When she cries in the night, Tommy whispers")
print("Baby, it's ok, someday")
print("We've got to hold on to what we've got")
print("It doesn't make a difference uf we make it or not")
print("We've got each other and that's a lot for love")
print("We'll giv it a shot")
print("Woah, we're half way there")
print("Woah, livin' on a prayer")
print("Take my hand, we'll make it I swear")
print("Woah, livin' on a prayer")
print("Livin' on a prayer")
print("Oh, we've got to hold on, ready or not")
print("You live for the fight when its all that you've got")
print("Woah we're half way there")
print("Woah, livin' on a prayer")
print("Woah, we're half way there")
print("Woah livin' on a prayer")
print("Take my hand, we'll make it I swear")
print("Woah, livin' on a prayer")
print("Woah, we're half way there")
print("Take my hand, we'll make it I swear")
print("Woah, livin' on a prayer")
